#! /bin/bash
sgpg=$(sed '1q;d' ~/.soc)
lgpg=$(sed '2q;d' ~/.soc)
bucket=$(sed '3q;d' ~/.soc)

pre="-----BEGIN PGP MESSAGE-----"
post="-----END PGP MESSAGE-----"

sortcmd="cat"
reverse=""

while [[ $# -gt 0 ]] ; do
  key="$1"
  case $key in
    -n)
      sortcmd="sort -k 4"
      ;;
    -t)
      sortcmd="sort -k 1,2"
      ;;
    -s)
      sortcmd="sort -k 3 -h"
      ;;
    -r)
      reverse=" -r"
      ;;
    -nr|-rn)
      sortcmd="sort -k 4"
      reverse=" -r"
      ;;
    -tr|-rt)
      sortcmd="sort -k 1,2"
      reverse=" -r"
      ;;
    -sr|-rs)
      sortcmd="sort -k 3 -h"
      reverse=" -r"
      ;;
    *)
      ;;
  esac
  shift
done

if [ "$sortcmd" == "cat" -a "$reverse" == " -r" ] ; then
  sortcmd="sort -k 4"
fi

aws s3 ls s3://$bucket | while read line ; do
  encname=$(echo $line | tr -s " " " " | cut -d " " -f 4)
  echo $line | tr -s " " " " | cut -d " " -f -3 | head -c -1 | tr " " "\t"
  echo -n "	"
  echo $encname | base32 -d | gpg -q --decrypt
done | numfmt --to=iec --field 3 -d "	" | column -t -s "	" | $sortcmd$reverse
