#! /bin/bash

# the total is approximate

socls | cut -f 5 -d ' ' | awk '/[0-9]$/{print $1;next};/[mM]$/{printf "%u\n", $1*(1024*1024);next};/[kK]$/{printf "%u\n", $1*1024;next}' | awk '{ sum += $1 } END { print sum }' | numfmt --to=iec
